const mongoose = require('mongoose');

// Define the schema for the Job model
const jobSchema = new mongoose.Schema({
    job_no: { type: String, required: true },
    order_id: { type: mongoose.Schema.Types.ObjectId, ref: 'order', required: true },
    branch_id: { type: mongoose.Schema.Types.ObjectId, ref: 'branch', required: true },
    customer_id: { type: mongoose.Schema.Types.ObjectId, ref: 'customer', required: true },
    rfq_id: { type: mongoose.Schema.Types.ObjectId, ref: 'rfq', required: true },
    offer_request_id: { type: mongoose.Schema.Types.ObjectId, ref: 'offer_request', required: true },
    delivery_charges: { type: Number, required: true },
    delivery_charges_without_tax: { type: Number, required: true },
    amount_for_driver: { type: Number, required: true },
    amount_to_fleet: { type: Number, required: true },
    amount_to_fleet_with_out_vat: { type: Number, required: true },
    job_type: { type: String, required: true },
    vehicle_category: { type: mongoose.Schema.Types.ObjectId, ref: 'vehicle_category', required: true },
    vehicle_type: { type: mongoose.Schema.Types.ObjectId, ref: 'vehicle_type', required: true },
    driver_id: { type: mongoose.Schema.Types.ObjectId, ref: 'driver', required: false },
    driver_assign_on: { type: Date, required: true },
    driver_per_job_commission: { type: Number, required: true },
    fleet_pay_driver_commission_payment: { type: Number, required: true },
    driver_current_earning_type: { type: String, default: "" },
    driver_user_type: { type: String, required: true },
    total_amount_for_driver: { type: Number, required: true },
    driver_commission_amount: { type: Number, required: true },
    driver_vat_on_commission_amount: { type: Number, required: true },
    vehicle_id: { type: mongoose.Schema.Types.ObjectId, ref: 'vehicle', required: true },
    company_id: { type: mongoose.Schema.Types.ObjectId, ref: 'company', required: true },
    no_of_pallet: { type: Number, required: true },
    assigned_to: { type: mongoose.Schema.Types.ObjectId, ref: 'user', required: true },
    job_start_date: { type: Date, required: true },
    job_end_date: { type: Date, required: true },
    is_driver_payment_settled: { type: Boolean, default: false },
    is_job_start: { type: Boolean, default: false },
    job_delivered: { type: Boolean, default: false },
    driver_submit_review: { type: Boolean, default: false },
    customer_submit_review: { type: Boolean, default: false },
    is_driver_job_item_picked_up: { type: Boolean, default: false },
    branch_latitude: { type: Number, required: true },
    branch_longitude: { type: Number, required: true },
    pick_up_location: { type: String, required: true },
    branch_name: { type: String, required: true },
    branch_contact_number: { type: String, required: true },
    branch_descriptions: {
        en: { branch_name: { type: String, required: true } },
        ar: { branch_name: { type: String, required: true } }
    },
    order_shipping_address: {
        location: { type: String, required: true },
        latitude: { type: Number, required: true },
        longitude: { type: Number, required: true }
    },
    order_billing_address: {
        location: { type: String, required: true },
        latitude: { type: Number, required: true },
        longitude: { type: Number, required: true }
    },
    order_no: { type: String, required: true },
    rfq_type: { type: String, required: true },
    driver_pickup_note: { type: String, default: "" },
    order_type: { type: String, required: true },
    admin_commission_percentage: { type: Number, required: true },
    admin_commission_settled: { type: Boolean, default: false },
    created: { type: Date, required: true },
    is_deleted: { type: Boolean, default: false },
    status: { type: String, required: true },
    is_quotation_received: { type: Boolean, default: false },
    driver_type: { type: String, required: true },
    is_fleet_payment_settled: { type: Boolean, default: false },
    is_approve_quotation_request: { type: Boolean, default: false },
    admin_commission_amount: { type: Number, required: true },
    quotation_amount: { type: Number, required: true },
    quotation_amount_with_vat: { type: Number, required: true },
    vat_amount_on_quotation: { type: Number, required: true },
    delivery_charges_vat: { type: Number, required: true },
    delivery_charges_vat_percentage: { type: Number, required: true },
    product_quantity: { type: Number, required: true },
    total_job_amount: { type: Number, required: true },
    job_start_at_by_driver: { type: Date },
    is_driver_reached_at_pickup: { type: Boolean, default: false },
    otp: { type: String, default: "" },
    is_customer_job_item_picked_up: { type: Boolean, default: false },
    is_driver_reached_dropoff_location: { type: Boolean, default: false },
    job_delivered_date: { type: Date },
    customer_id: { type: mongoose.Schema.Types.ObjectId, ref: 'customer', required: true },
    is_live: { type: Boolean, default: false },


});

const JobModel = mongoose.model('job', jobSchema, 'job');

module.exports = JobModel;
